@extends('layouts.admin')
@section('content')
@php
    $chartLabel = ['visitors' => 'visitantes', 'views' => 'páginas vistas', 'tracking' => 'búsquedas de paquetes'][$filters['chart_metric']];
    $maxTrend = max(1, (int) $trendSeries->max('total'), (int) $comparisonTrendSeries->max('total'));
    $formatDelta = fn ($delta) => $delta['value'] === null ? 'Sin base de comparación' : ($delta['direction'] === 'up' ? '+' : ($delta['direction'] === 'down' ? '−' : '')) . number_format($delta['value'], 1) . '% vs. comparación';
    $metrics = [
        ['Visitantes únicos', $summary['visitors_in_range'], 'Visitantes diferentes en el período', $summary['visitors_delta']],
        ['Páginas vistas', $summary['page_views_in_range'], 'Total de visitas a páginas', $summary['page_views_delta']],
        ['Búsquedas de envíos', $summary['tracking_searches_in_range'], 'Consultas de seguimiento', $summary['tracking_delta']],
        ['Interacciones', $summary['interactions_in_range'], 'Clics, búsquedas y cotizaciones', null],
    ];
    $makePoints = function ($series) use ($maxTrend) {
        return $series->values()->map(fn ($point, $i) => (20 + ($series->count() === 1 ? 380 : $i / ($series->count() - 1) * 760)) . ',' . (200 - $point->total / $maxTrend * 175))->implode(' ');
    };
@endphp
<div class="admin-shell stack">
    <header class="admin-topbar"><div class="admin-brand"><h1>Estadísticas del sitio</h1><p>Conoce las visitas y el uso de los servicios del sitio público.</p></div><a class="button button-ghost" href="{{ route('admin.analytics') }}">Últimos 14 días</a></header>
    <nav class="analytics-nav" aria-label="Secciones de estadísticas"><a href="#activity-chart">Evolución</a><a href="#site-usage">Uso del sitio</a><a href="#tracking-overview">Paquetes consultados</a><a href="#tracking-services">Por servicio</a><a href="#tracking-results">Resultados</a><a href="#live-activity">Actividad actual</a></nav>
    <section class="panel panel-body">
        <form class="analytics-filters" method="GET" action="{{ route('admin.analytics') }}">
            <div class="field"><label for="start-date">Desde</label><input id="start-date" type="date" name="start_date" min="{{ now()->subDays(365)->toDateString() }}" max="{{ now()->toDateString() }}" value="{{ $filters['start_date'] }}" required></div>
            <div class="field"><label for="end-date">Hasta</label><input id="end-date" type="date" name="end_date" min="{{ now()->subDays(365)->toDateString() }}" max="{{ now()->toDateString() }}" value="{{ $filters['end_date'] }}" required></div>
            <div class="field"><label for="compare-mode">Comparar con</label><select id="compare-mode" name="compare_mode">@foreach(['previous' => 'Período anterior', 'month' => 'Mes anterior', 'year' => 'Año anterior'] as $value => $label)<option value="{{ $value }}" @selected($filters['compare_mode'] === $value)>{{ $label }}</option>@endforeach</select></div>
            <div class="field"><label for="granularity">Agrupar por</label><select id="granularity" name="granularity">@foreach(['day' => 'Día', 'week' => 'Semana', 'month' => 'Mes'] as $value => $label)<option value="{{ $value }}" @selected($filters['granularity'] === $value)>{{ $label }}</option>@endforeach</select></div>
            <div class="field"><label for="chart-metric">Dato del gráfico</label><select id="chart-metric" name="chart_metric">@foreach(['visitors' => 'Visitantes', 'views' => 'Páginas vistas', 'tracking' => 'Búsquedas de paquetes'] as $value => $label)<option value="{{ $value }}" @selected($filters['chart_metric'] === $value)>{{ $label }}</option>@endforeach</select></div>
            <button type="submit" class="button button-primary">Aplicar filtros</button>
        </form>
        <div class="analytics-range"><span><strong>Período:</strong> {{ $filters['label'] }} · {{ $filters['days'] }} días</span><span><strong>Comparación:</strong> {{ $filters['previous_label'] }}</span></div>
    </section>
    <section class="stat-grid" aria-label="Resumen del período">
        @foreach($metrics as [$label, $value, $description, $delta])
            <article class="stat-card"><span>{{ $label }}</span><strong>{{ number_format($value) }}</strong><p>{{ $description }}</p>@if($delta)<small class="delta {{ $delta['direction'] }}">{{ $formatDelta($delta) }}</small>@endif</article>
        @endforeach
    </section>
    <section id="activity-chart" class="panel panel-body" x-data="{ chartView: 'bars' }">
        <div class="section-header"><div><h2 class="section-title">Evolución de {{ $chartLabel }}</h2><p class="section-copy">{{ $filters['chart_metric'] === 'visitors' ? 'Cada visitante se cuenta una vez por' : 'Total de eventos por' }} {{ ['day'=>'día','week'=>'semana','month'=>'mes'][$filters['granularity']] }}. {{ $filters['chart_metric'] === 'visitors' ? 'Puede aparecer en varios intervalos.' : 'Incluye las consultas repetidas.' }}</p></div><div class="view-switch" aria-label="Tipo de gráfico"><button type="button" :class="{active: chartView === 'bars'}" :aria-pressed="chartView === 'bars'" @click="chartView = 'bars'">Barras</button><button type="button" :class="{active: chartView === 'line'}" :aria-pressed="chartView === 'line'" @click="chartView = 'line'">Líneas</button></div></div>
        @if($trendSeries->sum('total') || $comparisonTrendSeries->sum('total'))
            <div x-show="chartView === 'bars'" class="analytics-chart" role="img" aria-label="Comparación de visitantes por intervalo; valores disponibles en la tabla de datos.">
                <div class="analytics-bars">
                @for($index = 0; $index < max($trendSeries->count(), $comparisonTrendSeries->count()); $index++)
                    @php($point = $trendSeries->get($index))
                    @php($previous = $comparisonTrendSeries->get($index))
                    <div class="chart-column"><span class="chart-value">{{ $point?->total ?? '—' }}</span><div class="chart-pair">@if($point)<div class="chart-bar" style="height:{{ $point->total / $maxTrend * 100 }}%" title="{{ $point->label }}: {{ $point->total }} {{ $chartLabel }}"></div>@endif @if($previous)<div class="chart-bar previous" style="height:{{ $previous->total / $maxTrend * 100 }}%" title="Comparación {{ $previous->label }}: {{ $previous->total }} {{ $chartLabel }}"></div>@endif</div><small>{{ $point?->label ?? '—' }}</small></div>
                @endfor
                </div>
            </div>
            <div x-cloak x-show="chartView === 'line'" class="analytics-chart">
                <svg class="chart-line" viewBox="0 0 800 230" role="img" aria-label="Evolución de visitantes del período y su comparación, cada uno en su escala temporal.">
                    <line x1="20" y1="200" x2="780" y2="200" stroke="#dfe6ef"/><line x1="20" y1="112" x2="780" y2="112" stroke="#edf1f6"/><line x1="20" y1="25" x2="780" y2="25" stroke="#edf1f6"/>
                    <text x="20" y="15" fill="#637188" font-size="11">{{ $maxTrend }}</text><text x="20" y="222" fill="#637188" font-size="11">{{ $trendSeries->first()?->label }}</text><text x="780" y="222" text-anchor="end" fill="#637188" font-size="11">{{ $trendSeries->last()?->label }}</text>
                    <polyline points="{{ $makePoints($comparisonTrendSeries) }}" fill="none" stroke="#bfcce1" stroke-width="3" stroke-dasharray="6 4"/>
                    <polyline points="{{ $makePoints($trendSeries) }}" fill="none" stroke="#245bb2" stroke-width="3"/>
                    @foreach($trendSeries as $index => $point)<circle cx="{{ 20 + ($trendSeries->count() === 1 ? 380 : $index / ($trendSeries->count() - 1) * 760) }}" cy="{{ 200 - $point->total / $maxTrend * 175 }}" r="3" fill="#245bb2"><title>{{ $point->label }}: {{ $point->total }}</title></circle>@endforeach
                </svg>
            </div>
            <div class="chart-legend"><span>Actual: {{ $filters['label'] }}</span><span>Comparación: {{ $filters['previous_label'] }}</span></div>
            <details class="history-details"><summary>Ver datos de los gráficos</summary><div style="overflow-x:auto"><table class="page-table"><thead><tr><th>Intervalo actual</th><th>{{ ucfirst($chartLabel) }}</th><th>Intervalo de comparación</th><th>Visitantes</th></tr></thead><tbody>@for($i = 0; $i < max($trendSeries->count(), $comparisonTrendSeries->count()); $i++)<tr><td>{{ $trendSeries->get($i)?->label ?? '—' }}</td><td>{{ $trendSeries->get($i)?->total ?? '—' }}</td><td>{{ $comparisonTrendSeries->get($i)?->label ?? '—' }}</td><td>{{ $comparisonTrendSeries->get($i)?->total ?? '—' }}</td></tr>@endfor</tbody></table></div></details>
        @else<div class="empty-note">No hay actividad registrada en estos períodos. Prueba otro rango de fechas.</div>@endif
    </section>
    <div class="analytics-grid" id="site-usage">
        <section class="panel panel-body"><div class="section-header"><div><h2 class="section-title">Páginas más visitadas</h2><p class="section-copy">Las 10 primeras · {{ number_format($summary['page_views_in_range']) }} vistas totales.</p></div></div><ol class="ranking">@forelse($topPages as $page)<li><div class="rank-head"><span>{{ $loop->iteration }}. {{ $page->page_name ?: $page->page_path }}<small>{{ $page->page_path }}</small></span><strong>{{ number_format($page->total) }}</strong></div><div class="rank-track"><i style="width:{{ $page->total / max(1, $topPages->max('total')) * 100 }}%"></i></div></li>@empty<li class="empty-note">Sin visitas registradas.</li>@endforelse</ol></section>
        <section class="panel panel-body"><div class="section-header"><div><h2 class="section-title">Uso de los servicios</h2><p class="section-copy">Acciones registradas durante el período.</p></div></div><ul class="ranking">@foreach(['Búsquedas de envíos' => $summary['tracking_searches_in_range'], 'Clics en botones' => $summary['cta_clicks_in_range'], 'Cotizaciones' => $summary['calculator_quotes_in_range']] as $label => $total)<li><div class="rank-head"><span>{{ $label }}</span><strong>{{ number_format($total) }}</strong></div><div class="rank-track"><i style="width:{{ $total / max(1, $summary['interactions_in_range']) * 100 }}%"></i></div></li>@endforeach</ul><p class="field-help">Cada acción cuenta como un evento; una persona puede realizar varias.</p></section>
        <section class="panel panel-body"><div class="section-header"><div><h2 class="section-title">Secciones con más actividad</h2><p class="section-copy">Las 10 primeras por clics, búsquedas y cotizaciones.</p></div></div><ol class="ranking">@forelse($topInteractions as $interaction)<li><div class="rank-head"><span>{{ str_replace('_', ' ', $interaction->section_name) }}</span><strong>{{ number_format($interaction->total) }}</strong></div><div class="rank-track"><i style="width:{{ $interaction->total / max(1, $topInteractions->max('total')) * 100 }}%"></i></div></li>@empty<li class="empty-note">Sin interacciones registradas.</li>@endforelse</ol></section>
        <section class="panel panel-body"><div class="section-header"><div><h2 class="section-title">Dispositivos</h2><p class="section-copy">Sesiones con visitas dentro del período.</p></div></div><ul class="ranking">@forelse($deviceBreakdown as $device)<li><div class="rank-head"><span>{{ ['desktop'=>'Computadora','mobile'=>'Teléfono','tablet'=>'Tableta','unknown'=>'Sin identificar'][$device->device] ?? $device->device }}</span><strong>{{ number_format($device->total) }} <small class="muted">({{ round($device->total / max(1, $deviceBreakdown->sum('total')) * 100) }}%)</small></strong></div><div class="rank-track"><i style="width:{{ $device->total / max(1, $deviceBreakdown->sum('total')) * 100 }}%"></i></div></li>@empty<li class="empty-note">Sin sesiones identificadas para este período.</li>@endforelse</ul></section>
    </div>
    @include('admin.analytics.details')
    @include('admin.analytics.tracking-summary')
    @include('admin.analytics.tracking-results')
    @include('admin.analytics.tracking')
    <div class="live-strip" id="live-activity"><span><i class="live-dot"></i><strong>Actividad actual</strong></span><span>{{ $summary['online_now'] }} sesiones del sitio</span><span>{{ $summary['apiweb_online_now'] }} sesiones internas</span><span>{{ $summary['visitors_today'] }} visitantes hoy</span><small>Sesiones: últimos 5 minutos · Actualizado a las {{ now()->format('H:i') }} · Recarga para actualizar</small></div>
    <div class="analytics-grid">
        <section class="panel panel-body"><div class="section-header"><div><h2 class="section-title">Sesiones del sitio público</h2><p class="section-copy">Hasta 30 sesiones activas; independiente del filtro de fechas.</p></div></div><div class="activity-list">@forelse($activeVisitors as $visitor)<article class="activity-item"><strong>{{ $visitor->current_title ?: 'Visitante del sitio' }}</strong><p>{{ $visitor->current_path ?: '/' }}</p><p>{{ $visitor->browser ?: 'Navegador sin identificar' }} · {{ $visitor->platform ?: 'Sistema sin identificar' }} · {{ $visitor->last_seen_at?->format('H:i:s') }}</p></article>@empty<div class="empty-note">No hay sesiones activas en este momento.</div>@endforelse</div></section>
        <section class="panel panel-body"><div class="section-header"><div><h2 class="section-title">Sesiones internas</h2><p class="section-copy">{{ $summary['apiweb_admin_online_now'] }} del panel · {{ $summary['apiweb_api_online_now'] }} de la API · hasta 12 recientes.</p></div></div><div class="activity-list">@forelse($apiwebSessions as $session)<article class="activity-item"><strong>{{ $session->user?->name ?: 'Usuario no disponible' }}</strong><p>{{ $session->guard_name === 'admin_web' ? 'Panel administrativo' : 'API' }} · {{ $session->last_seen_at?->format('H:i:s') }}</p><p>{{ $session->last_path ?: 'Sin ruta registrada' }}</p></article>@empty<div class="empty-note">No hay sesiones internas activas.</div>@endforelse</div></section>
    </div>
    <section class="panel panel-body"><div class="section-header"><div><h2 class="section-title">Actividad editorial y accesos</h2><p class="section-copy">Últimos movimientos registrados en el período seleccionado.</p></div></div><div class="activity-list">@forelse($recentActivity as $activity)<article class="activity-item"><strong>{{ $activity['title'] }}</strong><p>{{ $activity['subtitle'] }} · {{ $activity['actor'] }} · {{ $activity['occurred_at']?->format('d/m/Y H:i') }}</p><p>{{ $activity['detail'] }}</p></article>@empty<div class="empty-note">No hay movimientos registrados en este período.</div>@endforelse</div></section>
    <details class="panel panel-body analytics-help"><summary>Cómo interpretar estas estadísticas</summary><div class="grid grid-2" style="margin-top:18px"><div><strong>Visitantes y sesiones</strong><p class="section-copy">Un visitante se reconoce mediante el identificador de su navegador, no por su nombre. Una persona puede tener varios identificadores si cambia de dispositivo. Una sesión agrupa la actividad registrada con el mismo identificador de sesión.</p></div><div><strong>Consultas de paquetes</strong><p class="section-copy">Se registra lo que las personas buscan. Las consultas repetidas son búsquedas adicionales del mismo código dentro del período. Estos datos no informan si el paquete existe, fue entregado o si la consulta tuvo éxito.</p></div><div><strong>Comparación de períodos</strong><p class="section-copy">Los porcentajes comparan los totales de los rangos mostrados. Si el período anterior no tiene datos, no se calcula un porcentaje. Los meses pueden tener diferente duración.</p></div><div><strong>Datos disponibles</strong><p class="section-copy">Las estadísticas incluyen únicamente la actividad que envía el sitio. Los espacios vacíos significan que no hay información registrada para esa selección. Fechas y horarios: {{ config('app.timezone') }}.</p></div></div></details>
</div>
@endsection
