<header class="admin-topbar" id="tracking-overview"><div><h2 class="section-title">Seguimiento de paquetes</h2><p class="section-copy">Analiza los códigos consultados, la repetición de búsquedas y las horas de mayor uso.</p></div><a class="button button-secondary" href="{{ route('admin.analytics', array_merge(\Illuminate\Support\Arr::only($filters, ['start_date', 'end_date', 'compare_mode', 'granularity']), ['chart_metric' => 'tracking'])) }}#activity-chart">Ver evolución de búsquedas ↑</a></header>
<div class="stat-grid">
    <article class="stat-card"><span>Códigos distintos</span><strong>{{ number_format($summary['tracking_unique_codes']) }}</strong><p>Códigos escritos por los visitantes.</p></article>
    <article class="stat-card"><span>Visitantes que consultaron</span><strong>{{ number_format($summary['tracking_visitors']) }}</strong><p>Cada identificador se cuenta una vez.</p></article>
    <article class="stat-card"><span>Consultas repetidas</span><strong>{{ number_format($summary['tracking_repeat_searches']) }}</strong><p>Consultas adicionales al primer uso de cada código en el período.</p></article>
    <article class="stat-card"><span>Consultas por código</span><strong>{{ $summary['tracking_unique_codes'] ? number_format(($summary['tracking_searches_in_range'] - $summary['tracking_without_code']) / $summary['tracking_unique_codes'], 1) : '—' }}</strong><p>Promedio para códigos no vacíos.</p></article>
</div>
@if($summary['tracking_without_code'])<div class="notice notice-error">{{ number_format($summary['tracking_without_code']) }} consultas llegaron sin código. Se incluyen en el total de búsquedas, pero no en la lista de paquetes.</div>@endif
<section class="panel panel-body"><div class="section-header"><div><h2 class="section-title">Horas con más consultas</h2><p class="section-copy">Suma de búsquedas por hora durante el período. Horario: {{ config('app.timezone') }}.</p></div>@if($hourlyTracking->sum('total'))<span class="pill pill-off">Mayor actividad: {{ $hourlyTracking->sortByDesc('total')->first()->label }}</span>@endif</div>
    @if($hourlyTracking->sum('total'))<div class="analytics-chart"><div class="analytics-bars">@foreach($hourlyTracking as $hour)<div class="chart-column"><span class="chart-value">{{ $hour->total }}</span><div class="chart-pair"><div class="chart-bar" title="{{ $hour->label }}: {{ $hour->total }} consultas" style="height:{{ $hour->total / max(1, $hourlyTracking->max('total')) * 100 }}%"></div></div><small>{{ $hour->label }}</small></div>@endforeach</div></div>
    @else<div class="empty-note">Cuando se registren búsquedas podrás ver sus horarios aquí.</div>@endif
</section>
